# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEVOPS_PRIVATE_KEY }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        - script: |
            cd damarowahutu/devops-ci-cd
            git pull
            docker-compose down -t 0
            docker-compose build --no-cache
            docker-compose up -d

